server:
  port: 8087

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://${INVENTORY_DB_HOST:localhost}:${INVENTORY_DB_PORT:5438}/${INVENTORY_DB_NAME:inventory_db}
    username: ${INVENTORY_DB_USER:inventory}
    password: ${INVENTORY_DB_PASS:inventory123}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
