server:
  port: 8087

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://localhost:5437/inventory_db
    username: inventory_user
    password: inventory_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
