server:
  port: 8084

spring:
  application:
    name: workorder-service

  datasource:
    url: jdbc:postgresql://${WORKORDER_DB_HOST:localhost}:${WORKORDER_DB_PORT:5435}/${WORKORDER_DB_NAME:workorder_db}
    username: ${WORKORDER_DB_USER:workorder}
    password: ${WORKORDER_DB_PASS:workorder123}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
