server:
  port: 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: checklist_db
      username: root
      password: root123
      authentication-database: admin

logging:
  level:
    root: INFO
