version: "3.9"

services:

  auth-service:
    build:
      context: ../backend/auth-service
      dockerfile: Dockerfile
    container_name: ts-auth-service
    environment:
      SPRING_PROFILES_ACTIVE: dev-filestorage
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: tasksmart
      DB_USERNAME: dev_user
      DB_PASSWORD: dev_pass
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    ports:
      - "8081:8081"
    networks:
      - tasksmart

  user-service:
    build:
      context: ../backend/user-service
      dockerfile: Dockerfile
    container_name: ts-user-service
    environment:
      SPRING_PROFILES_ACTIVE: dev-filestorage
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: tasksmart
      DB_USERNAME: dev_user
      DB_PASSWORD: dev_pass
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    networks:
      - tasksmart

  work-order-service:
    build:
      context: ../backend/work-order-service
      dockerfile: Dockerfile
    container_name: ts-work-order-service
    environment:
      SPRING_PROFILES_ACTIVE: dev-filestorage
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: tasksmart
      DB_USERNAME: dev_user
      DB_PASSWORD: dev_pass
    depends_on:
      - postgres
    ports:
      - "8083:8083"
    networks:
      - tasksmart

  file-storage-service:
    build:
      context: ../backend/file-storage-service
      dockerfile: Dockerfile
    container_name: ts-file-storage-service
    environment:
      SPRING_PROFILES_ACTIVE: dev-filestorage
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: filestorage
      WORK_ORDER_URL: http://work-order-service:8083
      USER_SERVICE_URL: http://user-service:8082
    depends_on:
      - mongo
      - user-service
      - work-order-service
    ports:
      - "8084:8084"
    networks:
      - tasksmart

  gateway-service:
    build:
      context: ../backend/gateway-service
      dockerfile: Dockerfile
    container_name: ts-gateway
    environment:
      SPRING_PROFILES_ACTIVE: dev-filestorage
      FILE_STORAGE_SERVICE_URL: http://file-storage-service:8084
      USER_SERVICE_URL: http://user-service:8082
      AUTH_SERVICE_URL: http://auth-service:8081
    depends_on:
      - file-storage-service
      - auth-service
      - user-service
    ports:
      - "8080:8080"
    networks:
      - tasksmart

  mongo:
    image: mongo:7
    container_name: ts-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - tasksmart

volumes:
  mongo_data:

networks:
  tasksmart:
    external: true
