spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tasksmart}
    username: ${DB_USERNAME:dev_user}
    password: ${DB_PASSWORD:dev_pass}

  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:filestorage}

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

logging:
  level:
    root: INFO

server:
  port: ${SERVER_PORT:0}

workorder:
  files:
    endpoint: ${FILE_STORAGE_URL:http://localhost:8084}
